MCU = attiny84

COLOUR_TRIPLET = redTriplet

# clock fuse: external 16MHz crystal
LFUSE = 0xff
F_CPU = 8000000

PSRC = main.cpp

SRC = ../colour-triplets.c ../usart/usart-functions.c

EXTRAINCDIRS = .. ../usart

ARDLIBS = SoftwareSerial

include /d/dev/avr/treasure-hunt-2013/MakefileBase.makefile
