MCU = attiny85
# clock fuse: internal 8MHz osc
LFUSE = 0x62
F_CPU = 8000000

TARGET = main

PSRC = \
	main.cpp

SRC = 

NO_ARDUINO = 1

EXTRAINCDIRS = attiny85

include /d/dev/avr/treasure-hunt-2013/MakefileBase.makefile
