MCU = attiny84

# clock fuse: internal 8MHz osc
LFUSE = 0x62
F_CPU = 8000000

PSRC = main.cpp

SRC = 

EXTRAINCDIRS = .. 

ARDLIBS =
NO_ARDUINO = 1

include /d/dev/avr/treasure-hunt-2013/MakefileBase.makefile
