# AVRDUDE_PORT = com8
MCU = attiny85
# NO_ARDUINO = 1


TARGET = main_85
PSRC = main.cpp 
SRC =
PSRC += ../usart/usart-functions-attiny85.cpp
ARDLIBS = SoftwareSerial
EXTRAINCDIRS = .. ../usart


include /d/dev/avr/treasure-hunt-2013/Makefile.base
