MCU = attiny13
MCU = attiny13

# clock fuse: internal 9.6MHz osc
LFUSE = 0x6A
F_CPU = 9600000

PSRC = main.cpp

SRC = 

CFLAGS = 

EXTRAINCDIRS = ..

ARDLIBS =
NO_ARDUINO = 1

include /d/dev/avr/treasure-hunt-2013/MakefileBase.makefile
